CFLAGS=-O0 -g -Wall
PROGS=unix_d_send unix_d_server tcp_qq_srver tcp_client tcp_server tcp_qq_srverS tcp_echo_serverSR unix_d_sendO
JUNK=*.o *~ *.bak o oo ooo

all:	$(PROGS)

clean:
	rm -f $(JUNK) $(PROGS)
